language: java
sudo: required
services:
  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2    



before_install:
  - cd hml
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ../hml-naming-server
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ../hml-ronswanson-quotes
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ../hml-zuul-api
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  - cd ../hml-ronswanson-quotes
  - mvn test -B

after_success:
  - cd ..
  - docker build -t hyde009/hml ./hml
  - docker build -t hyde009/hml-naming-server ./hml-naming-server
  - docker build -t hyde009/hml-ronswanson-quotes ./hml-ronswanson-quotes
  - docker build -t hyde009/hml-zuul-api ./hml-zuul-api
  - docker build -t hyde009/nginx -f ./nginx/Dockerfile.basic ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hyde009/hml
  - docker push hyde009/hml-naming-server
  - docker push hyde009/hml-ronswanson-quotes
  - docker push hyde009/hml-zuul-api      
  - docker push hyde009/nginx


  


