sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2    

before_install:
  - openssl aes-256-cbc -K $encrypted_c618df825111_key -iv $encrypted_c618df825111_iv -in multi-k8s-234805-7ba6af97c4b5.json.enc -out multi-k8s-234805-7ba6af97c4b5.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-234805-7ba6af97c4b5.json
  - gcloud config set project multi-k8s-234805
  - gcloud config set compute/zone asia-east1-c
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
  